sewastaffai.wuz.web.id {
	import common_headers

	handle /api/* {
		reverse_proxy 127.0.0.1:8020
	}

	handle /webhooks/* {
		reverse_proxy 127.0.0.1:8020
	}

	handle {
		reverse_proxy 127.0.0.1:3020
	}
}
